config/routes.rb
Rails.application.routes.draw do
  apipie
  get 'home/index'
  resources :collections
  resources :products
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  
  get 'order', action: :index, controller: 'orders'


  namespace :admin do
    root "/admin/dashboard#index"
    resources :dashboard
    resources :products do
      member do
        put :approve
      end
    end
    resources :collections
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_collections
    has_many :collections, through: :product_collections
    mount_uploader :image, AvatarUploader
    belongs_to :user

    def get_image_url
        return self.image && self.image.url ? self.image.try(:url) : 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRxzT3N7-TEsb1AD_eU8B2TtTLryBLItF7cKw&usqp=CAU'
    end

    def is_pending?
        !self.status
    end

    def is_approved?
        self.status
    end
    
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :update_status]
  def index
    @products = Product.all.order('id DESC')
  end

  def show
  end

  def update
    if @product.update(product_params)
      redirect_to [:admin, @product], notice: 'Product was successfully update'
    else
      render :edit
    end
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to [:admin, @product], notice: 'Product was successfully created'
    else
      render :new
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy
    redirect_back(fallback_location: root_path)
  end

  def approve
    @product.update(status: true)

    new_product = ShopifyAPI::Product.new
    new_product.title = "Burton Custom Freestlye 151"
    new_product.product_type = "Snowboard"
    new_product.vendor = "Burton"
    new_product.save

    redirect_to admin_products_path, notice: 'Product is approved'
  end

  private
  def set_product
    @product = Product.find_by_id(params[:id])
  end
  def product_params
    params.require(:product).permit(:user_id, :name, :description, :image, :available_quantity, :price, :size, :status, :online)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = current_user.products.all
    # products = RestClient.get("https://#{ENV['SHOPIFY_API_KEY']}:#{ENV['SHOPIFY_API_PASSWORD']}@#{ENV['SHOPIFY_SHOP_NAME']}.myshopify.com/admin/api/2020-01/products.json")
    products = ShopifyAPI::Product.all
  end








  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:user_id, :name, :description, :image, :available_quantity, :price, :size, :status, :online)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model:[:admin, product],local:true) do |form| %>
  <div class="form-group">
    <%= form.label :name, for: "name" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter Product Name", id: "name" %>
  </div>
  <div class="form-group">
    <%= form.label :description, for: "description" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Enter Product Description", id: "description", rows: 8 %>
  </div>
  <div class="form-group">
    <%= form.label :image, for: "image" %>
    <%= form.file_field :image,  id: "image" %>
  </div>
  <div class="form-group">
    <%= form.label :stock, for: "stock" %>
    <%= form.text_field :stock, class: "form-control", placeholder: "Enter Product stock", id: "stock" %>
  </div>
  <div class="form-group">
    <%= form.label :price, for: "price" %>
    <%= form.text_field :price, class: "form-control", placeholder: "Enter Product price", id: "price" %>
  </div>
  <div class="form-group">
    <%= form.label :size, for: "size" %>
    <%= form.text_field :size, class: "form-control", placeholder: "Enter Product size", id: "size" %>
  </div>
  <div class="form-group">
    <%= form.label :online, for: "online" %><br>
    <%= form.check_box :online, id: "online", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :status, for: "status" %><br>
    <%= form.check_box :status, id: "status", class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<br>
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="row">
  <%= link_to "Create New Product", new_admin_product_path %><br><br>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Chef</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Image</th>
        <th scope="col">Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <th scope="row"><%= product.id %></th>
          <td><%= product.user.try(:email) %></td>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= image_tag product.get_image_url, width: '100', height: '100' %></td>
          <td><%= product.status ? 'Approved' : 'Pending' %></td>
          <td><%= link_to "Mark as Approved", approve_admin_product_path(product.id), method: :put if product.is_pending?  %></td>
          <td><%= link_to "View", admin_product_path(product.id) %></td>
          <td><%= link_to "Edit", edit_admin_product_path(product.id) %></td>
          <td><%= link_to 'Destroy', admin_product_path(product.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<div class="container">
    <div class="row">
        <div class="co-md-12">
            <div class="col-md-4">
                <%= image_tag @product.get_image_url, width: "200", height: "200" %>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-6">
                        Product Id
                    </div>
                    <div class="col-md-6">
                        <%= @product.id %>
                    </div>
                    <div class="col-md-6">
                        Product Name
                    </div>
                    <div class="col-md-6">
                        <%= @product.name %>
                    </div>
                    <div class="col-md-6">
                        Product Description
                    </div>
                    <div class="col-md-6">
                        <%= @product.description %>
                    </div>
                    <div class="col-md-6">
                        Product Status
                    </div>
                    <div class="col-md-6">
                        <%= @product.status %>
                    </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>